/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;


public class App {
	public String getGreeting() {
		try{
		String result = "";

		Class.forName("org.h2.Driver");
		Connection conn = DriverManager.getConnection("jdbc:h2:./app/src/main/resources/h2User", "", "");
		//Connection connHabit = DriverManager.getConnection("jdbc:h2:./app/src/main/resources/h2Habit", "", "");

		Statement Ustmt = conn.createStatement();
		Statement Hstmt = conn.createStatement();
		Statement Tstmt = conn.createStatement();

		String createUSER = "CREATE TABLE IF NOT EXISTS UserDB" + "(USERID INT PRIMARY KEY AUTO_INCREMENT(1,1) NOT NULL, NAME VARCHAR(255))";
		String createHABITS = "CREATE TABLE IF NOT EXISTS HabitDB " + "( HABITID INT PRIMARY KEY AUTO_INCREMENT(1,1) NOT NULL,USERID INT ,HABITNAME VARCHAR(255),HABITDESCRIPTION TEXT(500) ,HABITCYCLE INT)";
		String createTRACKER = "CREATE TABLE IF NOT EXISTS TrackerDB" + "(HABITID INT, STARTDATE DATE)";

		Ustmt.executeUpdate(createUSER);
		Ustmt.executeUpdate(createHABITS);
		Tstmt.executeUpdate(createTRACKER);

		//
		/*System.out.println("Type your username");
		Scanner myObj = new Scanner(System.in);
		//
		String username = myObj.nextLine();*/
		//String query = "INSERT INTO UserDB (NAME) VALUES('" + username + "')";
		String Habitquery = "INSERT INTO HabitDB (USERID,HABITNAME,HABITDESCRIPTION,HABITCYCLE)"
			 					+ "VALUES(1,'Drawing','You know just drawing casually',1)";
		String Trackerquery = "INSERT INTO TrackerDB (HABITID,STARTDATE) " + "VALUES(1,'1000-01-01')";
		//Ustmt.executeUpdate(query);
		Hstmt.executeUpdate(Habitquery);
		Tstmt.executeUpdate(Trackerquery);


		//stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Hello World!')");
		//stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Hello again!')");
		//stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Bye!')");

		ResultSet selectRS = Ustmt.executeQuery("SELECT * FROM UserDB");
		ResultSet selectRST = Ustmt.executeQuery("SELECT * FROM HabitDB,UserDB");
		ResultSet selectRSH = Hstmt.executeQuery("SELECT * FROM TrackerDB as T,HabitDB as H WHERE T.HABITID = H.HABITID");
		while (selectRS.next()) {
			System.out.printf("%d, %s\n", selectRS.getInt(1), selectRS.getString(2));
		}
		selectRSH = Ustmt.executeQuery("SELECT * FROM UserDB");
		while (selectRS.next()) {
			System.out.printf("%d, %s\n", selectRS.getInt(1), selectRS.getString(2));
		}

		/*while (selectRSH.next()) {
			selectRS.getInt(1);
			System.out.printf("%s, %s, %s, %s, %s\n", selectRS.getString(1), selectRS.getString(2),selectRS.getString(3),selectRS.getString(4),selectRS.getString(5));
		}*/
		//System.out.printf("%d, %s\n", selectRS.getInt(1), selectRS.getString(2));
		return result;
		}
		catch (Exception e) {
			System.out.println(e);
		}
		return "NULL";
	}

	public static void main(String[] args) {
			System.out.println(new App().getGreeting());
	}
}
